reorder_imports         = true
imports_granularity     = "Item"
group_imports           = "StdExternalCrate"
where_single_line       = true
trailing_comma          = "Vertical"
overflow_delimited_expr = true
wrap_comments           = true
comment_width           = 100
max_width               = 120
inline_attribute_width  = 0

merge_derives           = false

chain_width             = 100
